---

- hosts: all
  become: false
  tasks:

  - name: update repository index
    apk:
      update_cache: yes

  - name: install apache2 package
    apk:
      name: apache2
      state: latest

  - name: add php support for apache
    apk:
      name: libapache2-mod-php
      state: latest

